name: Build Aviator Bot APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Extrair projeto
        run: |
          mkdir build-project
          unzip AviatorBot_OnlineBuild.zip -d build-project

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.7'

      - name: Compilar APK
        working-directory: build-project
        run: gradle assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: AviatorBot-APK
          path: build-project/app/build/outputs/apk/debug/*.apk
